server:
  port: 8081

spring:
  application:
    name: junfukt-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${junfukt.config.db.address}/${junfukt.config.db.schema}?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${junfukt.config.db.username}
    password: ${junfukt.config.db.password}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall,slf4j
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

junfukt:
  config:
    db:
      address: 127.0.0.1:3306
      schema: my
      username: root
      password: root123456

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.babycare.bbs.provider.domain.entity
#  mapper-locations: classpath:mapper/*.xml
#  type-handlers-package: com.babycare.bbs.provider.infrastructure.typehandler